name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: actions/setup-node@v4
        with:
          install: npm i
          start: npm start
          test: npx cypress run
